### ISSUE TITLE
More docs pls

### ISSUE THREAD

**Issue by jamesplease** [jridgewell/minionette#2]
Computed, Model, etc.
# 

Update: these are unreleased! I see.

**Comment by jridgewell** [comment]
Those are coming once I release V2.

The short version is Model is written just to support Computed, which I stole from [Ember.js](http://emberjs.com/guides/object-model/computed-properties/).

Router is me embracing Marionette's AppRouter and Rails' Router. Instead of having multiple routers with one controller, I attach multiple controllers and have it forward appropriately.

**Comment by jamesplease** [comment]
Cool, cool. I'm just going to close this issue, as it's only a small part in the big v2 release.
